# Generated by Django 4.1 on 2022-09-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moviesdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('released_year', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('generes', models.CharField(max_length=150)),
            ],
        ),
    ]
